stock_app/__init__.py
from flask import Flask, render_template
from stock_app.blueprints.home import home
from stock_app.blueprints.stock import stock
from stock_app.config import configurations


def create_app(environment_name='dev'):
    app = Flask(__name__)
    app.config.from_object(configurations[environment_name])

    app.register_blueprint(home)
    app.register_blueprint(stock, url_prefix='/stock')

    @app.errorhandler(500)
    def handle_error(exception):
        return render_template('500.html'), 500

    return app

stock_app/blueprints/home.py
from flask import Blueprint, render_template, redirect, request, url_for

home = Blueprint('home', __name__)


@home.route('/')
def home_page():
    return render_template('home/index.html')


@home.route('/lookup', methods=['POST'])
def lookup():
    return redirect(url_for('stock.quote', ticker=request.form['ticker']))

stock_app/blueprints/stock.py
from flask import Blueprint, render_template, current_app
from stock_app.stock_data import fetch_income, fetch_price

stock = Blueprint('stock', __name__)


@stock.route("/<string:ticker>")
def quote(ticker):
    price = fetch_price(ticker, current_app.config)
    # return f"The Price of {ticker} is {price}".format(ticker=ticker, price=price)
    return render_template('stock/quote.html', ticker=ticker, stock_price=price)


@stock.route('/<string:ticker>/financials')
def financials(ticker):
    data = fetch_income(ticker, current_app.config)

    chart_data = [float(q["EPS"]) for q in data if q["EPS"]]
    chart_params = {"type": 'line',
                    "data": {
                        'labels': [q["date"] for q in data if q["EPS"]],
                        'datasets': [{'label': 'EPS', 'data': chart_data}]
                    }}
    return render_template('stock/financials.html', ticker=ticker, financials=data, chart_params=chart_params)

stock_app/templates/base_layout.html
<html>
<head>
    <title>
       {% block title %}View Stock Prices{% endblock %} -Stock APP
    </title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
</head>
<body>
    <nav class="navbar navbar-right bg-light justify-content-between">
        <a href="{{ url_for('home.home_page') }} " class="navbar-brand">Stock App</a>
        <ul class="navbar-nav mr_auto">
            <li class="nav-item {% if request.url_rule.endpoint == 'home_page' %} active {% endif %}">
                <a class="nav-link" href="{{ url_for('home.home_page') }}">Home</a>
            </li>
        </ul>
        <form method="POST" class="form-inline" action="{{ url_for('home.lookup') }}">
            <input class="form-control mr-sm-2" type="input" name="ticker" placeholder="AAPL" aria-label="Lookup"/>
            <button type="submit" class="btn btn-outline-success my-2 my-sm-0">Lookup</button>
        </form>
    </nav>

<div class="container mt-3">
    {% block content %}{% endblock %}
</div>
</body>
</html>

stock_app/templates/home/index.html
{% extends "base_layout.html" %}
{% block title %}Home Page{% endblock %}
{% block content %}

<div class="row">
<div class="col-sm">
    <h1>Welcome to StockApp</h1>
    <p>View Stock Prices</p>
</div>
    <div class="col">{% include 'shared/portfolio.html' %}</div>
</div>
{% endblock %}

stock_app/templates/macros.html
{% macro stock_quote_link(stock_ticker) %}
    <a href="{{ url_for('stock.quote', ticker=stock_ticker) }}">View: {{stock_ticker}}</a>
{% endmacro %}

stock_app/templates/shared/portfolio.html
{% from "macros.html" import stock_quote_link %}

<h2>Your Portfolio:</h2>
        <ul>
            {% for ticker in ['AAPL', 'GOOGL', 'FB', 'TSLA']%}
            <li>{{ stock_quote_link(ticker) }}</li>
            {% endfor%}
        </ul>

stock_app/templates/stock/financials.html
{% extends 'base_layout.html' %}
{% block title %} {{ticker}} financials {% endblock %}
{% block content%}
<div>
    <div class="row">
        <img src="https://quickchart.io/chart?width=500&height=200&c={{ chart_params }}" />
    </div>
    <table class="table mt-4">
        <thead>
            <tr>
                <th scope="col">As Of</th>
                <th scope="col">Revenue</th>
                <th scope="col">Gross Margin</th>
                <th scope="col">EPS</th>
            </tr>
        </thead>
        <tbody>
        {% for quarter in financials | reverse %}
            <tr>
                <th scope="row">{{ quarter["date"] }}</th>
                <td> {{ "${:,.0f}".format(quarter["Revenue"] | float) }}</td>
                <td> {{ ((quarter["Gross Margin"] | float) * 100 ) | round(2) }}%</td>
                <td> ${{ quarter["EPS"] }}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

stock_app/templates/stock/quote.html
{% extends "base_layout.html" %}
{% block title %}{{ticker}} Stock Quote{% endblock %}
{% block content %}
<div class="row">
    <div class="col-sm">
        <h1 class="mb-3">{{ticker | upper}}</h1>
    <hr />
        <h2>Price: ${{stock_price}}</h2>
    </div>
    <div class="col">
        {% include 'shared/portfolio.html' %}
    </div>
    <div class="col">
        <a href="{{ url_for('stock.financials', ticker=ticker) }} " class="navbar-brand">Financial Report</a>
    </div>
</div>
{% endblock %}